type University = {
  [key: string]: string;
};

const UniversityList: University = {
  "Princeton University": "princeton.edu",
  "Massachusetts Institute of Technology": "mit.edu",
  "Harvard University": "harvard.edu",
  "Stanford University": "stanford.edu",
  "Yale University": "yale.edu",
  "University of Pennsylvania": "upenn.edu",
  "California Institute of Technology": "caltech.edu",
  "Duke University": "duke.edu",
  "Brown University": "brown.edu",
  "Johns Hopkins University": "jhu.edu",
  "Northwestern University": "northwestern.edu",
  "Columbia University": "columbia.edu",
  "Cornell University": "cornell.edu",
  "University of Chicago": "uchicago.edu",
  "University of California, Berkeley": "berkeley.edu",
  "University of California, Los Angeles": "ucla.edu",
  "Rice University": "rice.edu",
  "Dartmouth College": "dartmouth.edu",
  "Vanderbilt University": "vanderbilt.edu",
  "University of Notre Dame": "nd.edu",
  "University of Michigan": "umich.edu",
  "Georgetown University": "georgetown.edu",
  "University of North Carolina at Chapel Hill": "unc.edu",
  "Carnegie Mellon University": "cmu.edu",
  "Emory University": "emory.edu",
  "University of Virginia": "virginia.edu",
  "Washington University in St. Louis": "wustl.edu",
  "University of California, Davis": "ucdavis.edu",
  "University of California, San Diego": "ucsd.edu",
  "University of Florida": "ufl.edu",
  "University of Southern California": "usc.edu",
  "University of Texas at Austin": "utexas.edu",
  "Georgia Institute of Technology": "gatech.edu",
  "University of California, Irvine": "uci.edu",
  "New York University": "nyu.edu",
  "University of California, Santa Barbara": "ucsb.edu",
  "University of Illinois Urbana-Champaign": "illinois.edu",
  "University of Wisconsin, Madison": "wisc.edu",
  "Boston College": "bc.edu",
  "Tufts University": "tufts.edu",
  "University of Washington": "uw.edu",
  "Boston University": "bu.edu",
  "The Ohio State University": "osu.edu",
  "Purdue University": "purdue.edu",
  "University of Maryland": "umd.edu",
  "Lehigh University": "lehigh.edu",
  "Texas A&M University": "tamu.edu",
  "University of Georgia": "uga.edu",
  "University of Rochester": "rochester.edu",
  "Virginia Tech": "vt.edu",
  "Wake Forest University": "wfu.edu",
  "Case Western Reserve University": "case.edu",
  "Florida State University": "fsu.edu",
  "Northeastern University": "northeastern.edu",
  "University of Minnesota": "umn.edu",
  "William & Mary": "wm.edu",
  "Stony Brook University": "stonybrook.edu",
  "University of Connecticut": "uconn.edu",
  "Brandeis University": "brandeis.edu",
  "Michigan State University": "msu.edu",
  "North Carolina State University": "ncsu.edu",
  "Pennsylvania State University": "psu.edu",
  "Rensselaer Polytechnic Institute": "rpi.edu",
  "Santa Clara University": "scu.edu",
  "University of California, Merced": "ucmerced.edu",
  "George Washington University": "gwu.edu",
  "Syracuse University": "syr.edu",
  "University of Massachusetts, Amherst": "umass.edu",
  "University of Miami": "miami.edu",
  "University of Pittsburgh": "pitt.edu",
  "Villanova University": "villanova.edu",
  "Binghamton University": "binghamton.edu",
  "Indiana University, Bloomington": "iub.edu",
  "Tulane University": "tulane.edu",
  "Colorado School of Mines": "mines.edu",
  "Pepperdine University": "pepperdine.edu",
  "Stevens Institute of Technology": "stevens.edu",
  "University at Buffalo": "buffalo.edu",
  "University of California, Riverside": "ucr.edu",
  "University of Delaware": "udel.edu",
  "Rutgers University": "rutgers.edu",
  "University of California, Santa Cruz": "ucsc.edu",
  "University of Illinois Chicago": "uic.edu",
  "Worcester Polytechnic Institute": "wpi.edu",
  "Clemson University": "clemson.edu",
  "Marquette University": "marquette.edu",
  "New Jersey Institute of Technology": "njit.edu",
  "Fordham University": "fordham.edu",
  "Southern Methodist University": "smu.edu",
  "Temple University": "temple.edu",
  "University of South Florida": "usf.edu",
  "Auburn University": "auburn.edu",
  "Baylor University": "baylor.edu",
  "Gonzaga University": "gonzaga.edu",
  "Loyola Marymount University": "lmu.edu",
  "University of Iowa": "uiowa.edu",
  "Drexel University": "drexel.edu",
  "Illinois Institute of Technology": "iit.edu",
  "Rochester Institute of Technology": "rit.edu",
  "For Development": "gmail.com",
};

export default UniversityList;
