name: build_and_deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Build
        run: |
          cd server
          pnpm i
          tsc -b

  deploy:
    needs: build
    runs-on:
      - self-hosted
    steps:
      - name: Deploy the latest build
        run: |
          cd server
          pm2 kill
          pm2 start ./dist/index.js
