name: build_and_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Build
        env:
          ENV: ${{ secrets.ENV }}
        run: |
          cd server
          pnpm i
          echo "${{ENV}}" > .env
          pnpm prisma migrate dev --name deploy
          tsc -b

  deploy:
    needs: build
    runs-on:
      - self-hosted
    steps:
      - name: Deploy the latest build
        run: |
          cd server
          pm2 kill
          pm2 start ./dist/index.js
